---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: vsan-default-storage-policy
  resources:
    requests:
      storage: 200Mi
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
    tier: web
  name: nginx-pod
  namespace: default
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - name: nginx-pvc
      mountPath: "/usr/share/nginx/html/"
  volumes:
  - name: nginx-pvc
    persistentVolumeClaim:
      claimName: nginx-pvc
